import type { Color } from "@/shared/types";

const colors: Color[] = [
  { value: "#FF0000", name: "red" },
  { value: "#FF4500", name: "orangered" },
  { value: "#FF6347", name: "tomato" },
  { value: "#FF7F50", name: "coral" },
  { value: "#DC143C", name: "crimson" },
  { value: "#B22222", name: "firebrick" },
  { value: "#8B0000", name: "darkred" },
  { value: "#FF8C00", name: "darkorange" },
  { value: "#FFA500", name: "orange" },
  { value: "#FF8D1A", name: "vivid_orange" },
  { value: "#FFD700", name: "gold" },
  { value: "#FFFF00", name: "yellow" },
  { value: "#FFFF33", name: "vivid_lime" },
  { value: "#FFFACD", name: "lemonchiffon" },
  { value: "#FAFAD2", name: "lightgoldenrodyellow" },
  { value: "#98FB98", name: "palegreen" },
  { value: "#00FF00", name: "lime" },
  { value: "#00FA9A", name: "mediumspringgreen" },
  { value: "#7CFC00", name: "lawngreen" },
  { value: "#7FFF00", name: "chartreuse" },
  { value: "#ADFF2F", name: "greenyellow" },
  { value: "#32CD32", name: "limegreen" },
  { value: "#228B22", name: "forestgreen" },
  { value: "#008000", name: "green" },
  { value: "#006400", name: "darkgreen" },
  { value: "#00FF7F", name: "springgreen" },
  { value: "#00CED1", name: "darkturquoise" },
  { value: "#5F9EA0", name: "cadetblue" },
  { value: "#008080", name: "teal" },
  { value: "#00FFFF", name: "cyan" },
  { value: "#00BFFF", name: "deepskyblue" },
  { value: "#1E90FF", name: "dodgerblue" },
  { value: "#87CEEB", name: "skyblue" },
  { value: "#4682B4", name: "steelblue" },
  { value: "#4169E1", name: "royalblue" },
  { value: "#0000FF", name: "blue" },
  { value: "#00008B", name: "darkblue" },
  { value: "#8A2BE2", name: "blueviolet" },
  { value: "#4B0082", name: "indigo" },
  { value: "#6A5ACD", name: "slateblue" },
  { value: "#9932CC", name: "darkorchid" },
  { value: "#9400D3", name: "darkviolet" },
  { value: "#FF00FF", name: "fuchsia" },
  { value: "#FF1493", name: "deeppink" },
  { value: "#FF69B4", name: "hotpink" },
  { value: "#DB7093", name: "palevioletred" },
  { value: "#C71585", name: "mediumvioletred" },
  { value: "#DDA0DD", name: "plum" },
  { value: "#EE82EE", name: "violet" },
];

export default colors;
